<div class="nav-submenu panel layout-row short" data-id="primaryLink1_Perspectives" data-linkcomponentname="primary nav" data-analytics-module-name="primary nav" role="none">
                                        
                                        <div class="gh-item nav-submenu-label collapsed" role="menuitem" data-target="#primaryLink1_Perspectives" data-parent="#navigation-menu" tabindex="0" aria-label="Perspectives" aria-haspopup="true" aria-expanded="false" data-linkcomponentname="primary nav" data-analytics-module-name="primary nav" data-cell="GH1" data-analytics-link-name="perspectives" data-analytics-content-type="nav/paginate" data-toggle="collapse" style="">
                                            <span class="nav-submenu-label-text">
Perspectives                                            </span>
                                            <div class="expand-collapse-container visible-md visible-xs visible-sm">
                                                <span class="ion-chevron-down"></span>
                                            </div>
                                        </div>
                                        <div class="secondary-navs panel-collapse collapse" id="primaryLink1_Perspectives" style="padding-top: 0px; margin-top: 0px;" aria-expanded="false">
                                            <div class="secondary-nav-menu" style="height: auto;">
                                                <div class="nav-item-links" style="width:100%;">
                                                        <ul class="no-l3   col-sm-12 secondaryCounter" data-secondarylinkcount="11" role="menu" aria-label="Perspectives" data-lastrow="2">
                                                            <li class="first-secondary-item" data-analytics-module-name="secondary nav" role="none">
                                                                <a href="/fr-fr/insights/voices" class="hidden-lg" data-linkcomponentname="secondary nav" role="menuitem" data-analytics-link-name="visions sur le changement" data-analytics-content-type="nav/paginate"> Visions sur le Changement</a>
                                                                <span class="col-sm-3 visible-lg secondary-hyperlink" role="none">
                                                                    <a href="/fr-fr/insights/voices" class="overview-link cta-arrow hidden-md hidden-sm hidden-xs displayInline" data-linkcomponentname="secondary nav" role="menuitem" data-analytics-link-name="visions sur le changement" data-analytics-content-type="nav/paginate"> Visions sur le Changement</a>
                                                                </span>
                                                                                                                            </li>
                                                                                                                                <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/competitive-agility-index" aria-label="Agilité Compétitive" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="A0" data-analytics-link-name="agilité compétitive" data-analytics-content-type="nav/paginate">Agilité Compétitive</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/us-en/services/blockchain-index" aria-label="Blockchain" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="B0" data-analytics-link-name="blockchain" data-analytics-content-type="nav/paginate">Blockchain</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/cloud-computing-index" aria-label="Cloud" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="C0" data-analytics-link-name="cloud" data-analytics-content-type="nav/paginate">Cloud</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/about/company/coronavirus-business-economic-impact" aria-label="COVID-19" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="D0" data-analytics-link-name="covid-19" data-analytics-content-type="nav/paginate">COVID-19</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/cyber-security-index" aria-label="Cyber-résilience" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="A1" data-analytics-link-name="cyber-résilience" data-analytics-content-type="nav/paginate">Cyber-résilience</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/us-en/insights/future-systems/future-systems-index" aria-label="Future Systems" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="B1" data-analytics-link-name="future systems" data-analytics-content-type="nav/paginate">Future Systems</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/industry-x-0-index" aria-label="Industry X" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="C1" data-analytics-link-name="industry x" data-analytics-content-type="nav/paginate">Industry X</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/artificial-intelligence-summary-index" aria-label="Intelligence Artificielle" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="D1" data-analytics-link-name="intelligence artificielle" data-analytics-content-type="nav/paginate">Intelligence Artificielle</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/us-en/insights/future-workforce-index" aria-label="Talents de demain" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="A2" data-analytics-link-name="talents de demain" data-analytics-content-type="nav/paginate">Talents de demain</a> </li>
                                                                    <li class="col-sm-3 secondary-item" data-analytics-module-name="secondary nav" role="none" style=""><a href="/fr-fr/insights/podcast-index" aria-label="Podcasts" data-linkcomponentname="Secondary nav" role="menuitem" data-cell="B2" data-analytics-link-name="podcasts" data-analytics-content-type="nav/paginate">Podcasts</a> </li>

                                                        </ul>

                                                </div>
                                            </div>
                                        </div>
                                    </div>